[Coinbase subspec] Add missing dependency on Braintree/API
Caught with `pod lib lint`
- ERROR | [Braintree/Coinbase] [xcodebuild]
  braintree-ios/Braintree/Coinbase/@Public/BTCoinbase.h:3:9:
  fatal error: 'BTAppSwitching.h' file not found